steps:
  - label: Examples Test
    agents:
        queue: moc-cpu
    soft_fail: false
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: -10  # Agent was lost
          limit: 1
    commands:
      - sleep 6000
      - cd /vllm-workspace/examples
      - pip install tensorizer # for tensorizer test
      - python3 offline_inference/basic.py
      - python3 offline_inference/cpu_offload.py
      - python3 offline_inference/chat.py
      - python3 offline_inference/prefix_caching.py
      - python3 offline_inference/llm_engine_example.py
      - python3 offline_inference/vision_language.py
      - python3 offline_inference/vision_language_multi_image.py
      - python3 other/tensorize_vllm_model.py --model facebook/opt-125m serialize --serialized-directory /tmp/ --suffix v1 && python3 other/tensorize_vllm_model.py --model facebook/opt-125m deserialize --path-to-tensors /tmp/vllm/facebook/opt-125m/v1/model.tensors
      - python3 offline_inference/encoder_decoder.py
      - python3 offline_inference/classification.py
      - python3 offline_inference/embedding.py
      - python3 offline_inference/scoring.py
      - python3 offline_inference/profiling.py --model facebook/opt-125m run_num_steps --num-steps 2
    plugins:
      - kubernetes:
          podSpec:
            priorityClassName: ci
            containers:
            - image: public.ecr.aws/q9t5s3a7/vllm-ci-postmerge-repo:c92acb9693c0504d7dabed2a0251b9f5d4ddaebb
              #resources:
              #  requests:
              #  nvidia.com/gpu: 2
              #  limits:
              #    nvidia.com/gpu: 2
              #volumeMounts:
              #- name: shm-volume
              #  mountPath: /dev/shm
            #volumes:
            #- name: shm-volume
            #  persistentVolumeClaim:
            #    claimName: shm-pvc
            #tolerations:
            #- key: "nvidia.com/gpu.product"
            #  operator: "Equal"
            #  value: "NVIDIA-A100-SXM4-40GB"
            #  effect: "NoSchedule"
