steps:
  - label: Distributed Tests (4 GPUs)
    agents:
        queue: moc-a100
    soft_fail: false
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: -10  # Agent was lost
          limit: 1
    commands:
      - cd /vllm-workspace/tests
      - pytest -v -s distributed/test_utils.py
      - pytest -v -s compile/test_basic_correctness.py
      - pytest -v -s distributed/test_pynccl.py
      - pytest -v -s spec_decode/e2e/test_integration_dist_tp4.py
      # TODO: create a dedicated test section for multi-GPU example tests
      # when we have multiple distributed example tests
      - python3 ../examples/offline_inference/rlhf.py
    plugins:
      - kubernetes:
          podSpec:
            priorityClassName: ci
            containers:
            - image: public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:4cfd785c7803bcbf65fabbd37a5ff7d5b8bb1502
              resources:
                requests:
                nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              volumeMounts:
              - name: shm-volume
                mountPath: /dev/shm
            volumes:
            - name: shm-volume
              persistentVolumeClaim:
                claimName: shm-pvc
            tolerations:
            - key: "nvidia.com/gpu.product"
              operator: "Equal"
              value: "NVIDIA-A100-SXM4-40GB"
              effect: "NoSchedule"
