steps:
  - label: Samplers Test
    agents:
        queue: moc-cpu
    soft_fail: false
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: -10  # Agent was lost
          limit: 1
    commands:
      - cd /vllm-workspace/tests
      - pytest -v -s samplers
      - VLLM_USE_FLASHINFER_SAMPLER=1 pytest -v -s samplers
    plugins:
      - kubernetes:
          podSpec:
            priorityClassName: ci
            containers:
            - image: public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:4cfd785c7803bcbf65fabbd37a5ff7d5b8bb1502
              resources:
                requests:
                nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              #volumeMounts:
              #- name: shm-volume
              #  mountPath: /dev/shm
            #volumes:
            #- name: shm-volume
            #  persistentVolumeClaim:
            #    claimName: shm-pvc
            tolerations:
            - key: "nvidia.com/gpu.product"
              operator: "Equal"
              value: "NVIDIA-A100-SXM4-40GB"
              effect: "NoSchedule"
